# Generated by Django 5.2.3 on 2025-07-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='plan_details',
            field=models.TextField(blank=True, help_text='Recommended workout plan details'),
        ),
    ]
